<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use OwenIt\Auditing\AuditingTrait;

class VersionPauta extends Model
{
    use SoftDeletes;
    use AuditingTrait;

     protected $fillable = [
         'name',
         'slug'
     ];


     public static function boot()
     {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function (VersionPauta $versionPauta){
            $versionPauta->slug = str_slug($versionPauta->name);
        });

        static::updating(function (VersionPauta $versionPauta){
            $versionPauta->slug = str_slug($versionPauta->name);
        });

     }

     public function structurePauta()
     {
         return $this->hasMany(Structurepautum::class);
     }




}
