name: Build and dependencies

on:
  push:
    branches: [ develop ]

jobs:
  composer-dependencies:

    runs-on: ubuntu-20.04

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '7.4.3'
      - uses: actions/checkout@v2
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Generate key
        run: php artisan key:generate
      - name: Run migrations
        with:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          echo "$DB_USERNAME"
#        run: php artisan migrate
      - name: Run seeds
        run: php artisan db:seed
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

  build:

    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [ 6.x ]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: |
          npm install
          gulp
